libnetconf4
CESNET/libnetconf2 pull request #442
Opened 2023-10-19 08:02 UTC by Roytak

New libnetconf2 API

2023-10-19 11:23 UTC, michalvasko requested changes

2023-10-19 11:23 UTC, michalvasko commented on tests/CMakeLists.txt
> +# set(client_tests test_client test_client_messages)
Meaningful client tests may be kept but should be reorganized and part of the main test suite.

2023-10-25 09:23 UTC, Roytak commented on src/server_config.c
> +    }
I think it should be enough, but I added `pthread_mutex_lock(&client.lock);` for safety. Shouldn't be necessary though.

2023-10-26 13:29 UTC, michalvasko approved these changes

2023-10-30 07:23 UTC, michalvasko requested changes

2023-10-30 07:23 UTC, michalvasko commented on .github/workflows/ci.yml
> +          ctest --output-on-failure
Keep EOLs.

2023-10-30 07:23 UTC, michalvasko commented on .github/workflows/devel-push.yml
> +        if: ${{ matrix.config.name == 'Codecov' }}
Removed EOL.

2023-11-02 14:54 UTC, michalvasko approved these changes

2023-11-03 14:03 UTC, merged